### ISSUE TITLE
Can I contact you quickly?

### ISSUE THREAD

**Issue by ciscoxll** [peternavr/godiscordbot#1]
My wechat :`****`

**Comment by ciscoxll** [comment]
@clanstyles Can I contact you quickly?

**Comment by peternavr** [comment]
yeah I don't have wechat. Do you have something else?

**Comment by ciscoxll** [comment]
@clanstyles You can try this
1. Convert data to utf8 before inserting tidb and insert.
2. Filter the special characters in the insertion if it does not affect the business.

**Comment by ciscoxll** [comment]
@clanstyles google hangouts :`**********`?
